name: "Bypass Scan Failure Approval Issues Closed"
on:
  issues:
    types: [closed]
jobs:
  validate:
    name: Validate Issue
    if: contains(github.event.issues.labels.*.name, 'bug')
    runs-on: ubuntu-latest
    steps: 
      - run: |
          echo "Now running something"
          
          
